check3d.exe: check3d.c line.obj hline.obj vline.obj
	tcc -G -O -Z -B check3d line.obj hline.obj vline.obj

line.obj: line.asm
	tasm /mx line.asm

hline.obj: hline.asm
	tasm /mx hline.asm

vline.obj: vline.asm
	tasm /mx vline.asm
