cgademo3.exe: cgademo3.c line.obj circle.obj ellipse.obj
	tcc -G -O -Z cgademo3 line.obj circle.obj ellipse.obj

line.obj: line.asm
	tasm /mx line.asm

circle.obj: circle.asm
	tasm /mx circle.asm

ellipse.obj: ellipse.asm
	tasm /mx ellipse.asm