envoight.exe: envoight.c ship.obj sprite.obj graphics.obj page.obj enemy1.obj enemy2.obj enemy3.obj ammo.obj
	tcc -B -G -O -Z envoight ship.obj sprite.obj graphics.obj page.obj enemy1.obj enemy2.obj enemy3.obj ammo.obj

sprite.obj: sprite.c sprite.h
	tcc -B -G -O -Z -c sprite.c

graphics.obj: graphics.c graphics.h
	tcc -B -G -O -Z -c graphics.c

page.obj: page.c page.h
	tcc -B -G -O -Z -c page.c

ship.obj: ship.c
	tcc -B -G -O -Z -c ship.c

enemy1.obj: enemy1.c
	tcc -B -G -O -Z -c enemy1.c

enemy2.obj: enemy2.c
	tcc -B -G -O -Z -c enemy2.c

ammo.obj: ammo.c
	tcc -B -G -O -Z -c ammo.c

enemy3.obj: enemy3.c
	tcc -B -G -O -Z -c enemy3.c

